---
title: "ASCR Tutorial"
output: 
  learnr::tutorial:
    includes:
      css: css/styles.css
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(shiny)
library(tidyverse)
library(DT)
library(spatstat)
library(raster)
library(ggimage)

frog_image <- "images/frogGraphic.png"
micro_image <- "images/micro.png"

# Detection function
hazard_halfnormal_detection <- function(sigma, lam0, d) {
  prob <- 1 - exp(-lam0 * exp(-d * (2 * sigma^2)))
  return(prob)
}

calculate_prob_succ <- function(dataframe, detector) {
  # Calculate distance between each point and the detector
  dataframe$distance <- sqrt((dataframe$x - detector$x)^2 + (dataframe$y - detector$y)^2)

  # Define distance intervals and associated probabilities
  distance_intervals <- seq(0, 5, 0.1)
  probabilities <- hazard_halfnormal_detection(1.5, 15, distance_intervals)

  # Create a new column to store the probabilities
  dataframe$prob_succ <- NA

  # Create a new column to store the probabilities
  dataframe$det <- NA

  # Iterate over each row and assign the corresponding probability based on the distance
  for (i in 1:nrow(dataframe)) {
    distance <- dataframe$distance[i]

    # Find the index of the interval where the distance falls
    interval_index <- findInterval(distance, distance_intervals)

    # Assign the probability based on the interval index
    dataframe$prob_succ[i] <- probabilities[interval_index]

    dataframe$det[i] <- rbinom(1, 1, dataframe$prob_succ[i])
  }

  # Remove the distance column
  dataframe$distance <- NULL

  # Mutate each element based on the probability using the binomial distribution
  # dataframe <- dataframe %>%
  #   mutate(result = rbinom(n(), size=1, prob_succ))

  return(dataframe$det)
}

# Microphone array

# Define the range of x and y
x_range <- seq(1, 4, by = 1)
y_range <- seq(2, 3, by = 1)

# Create the grid of points
microphones <- expand.grid(x = x_range, y = y_range)
```



```{sass, echo = FALSE}
$color1: #668BA4
$color2: #FEFFDF
div
  &.learnBox
    border-color: $color1
    border-style: solid
    background-color: rgba(151, 203, 169,.5)
    width: 100%
    padding: 0.5em
    border-radius: 10px
    margin: 0 auto 
    strong
      color: $color1
      
  &.defBox
    border-color: $color1
    border-style: solid
    width: 100%
    padding: 0.5em
    border-radius: 5px
    margin: 0 auto 
    strong
      color: $color1

```


## Welcome 
::: mybox
Special **important** content
:::


```{r, child='Chapter1.Rmd'}
```

```{r, child='Chapter2.Rmd'}
```

```{r, child='Chapter3.Rmd'}
```

```{r, child='Chapter4.Rmd'}
```

```{r, child='Chapter5.Rmd'}
```
